# Generated by Django 5.2.9 on 2025-12-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_content",
                    models.TextField(blank=True, help_text="Raw log file content"),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="api.log",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host",
                "verbose_name_plural": "Hosts",
                "ordering": ["hostname"],
                "unique_together": {("log", "hostname")},
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("changed", "Changed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("tasks_ok", models.IntegerField(default=0)),
                ("tasks_changed", models.IntegerField(default=0)),
                ("tasks_failed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="api.host",
                    ),
                ),
            ],
            options={
                "verbose_name": "Play",
                "verbose_name_plural": "Plays",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["host", "-date"], name="api_play_host_id_78cea4_idx"
                    ),
                    models.Index(
                        fields=["status", "-date"], name="api_play_status_a80565_idx"
                    ),
                ],
            },
        ),
    ]
