# Generated by Django 5.2.9 on 2026-01-26 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_add_play_line_number_and_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Task order (0-indexed)"
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Line number in raw log where task starts",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("changed", "Changed"),
                            ("failed", "Failed"),
                            ("skipping", "Skipped"),
                            ("unreachable", "Unreachable"),
                            ("ignored", "Ignored"),
                            ("rescued", "Rescued"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True, help_text="Error message when task fails", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_list",
                        to="api.play",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["play", "order"], name="api_task_play_id_0fb2aa_idx"
                    ),
                    models.Index(fields=["status"], name="api_task_status_2aef03_idx"),
                ],
            },
        ),
    ]
