# Generated by Django 5.2.9 on 2026-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_task_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("changed", "Changed"),
                    ("failed", "Failed"),
                    ("fatal", "Fatal"),
                    ("skipping", "Skipped"),
                    ("unreachable", "Unreachable"),
                    ("ignored", "Ignored"),
                    ("rescued", "Rescued"),
                ],
                db_index=True,
                max_length=15,
            ),
        ),
    ]
